python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 16, "d_model": 24, "horizon": 96, "lr": 0.01, "norm": true, "seq_len": 336, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 16, "d_model": 24, "horizon": 192, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 64, "d_model": 12, "horizon": 336, "lr": 0.015, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 16, "d_model": 64, "horizon": 720, "lr": 0.01, "norm": true, "seq_len": 96, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/MoFo"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 64, "d_model": 12, "horizon": 96, "lr": 0.015, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 16, "d_model": 128, "horizon": 192, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 64, "d_model": 12, "horizon": 336, "lr": 0.015, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 16, "d_model": 128, "horizon": 720, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/MoFo"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 96, "lr": 0.01, "norm": true, "seq_len": 336, "patience": 10, "periodic": 96, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 192, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 96, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 336, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 96, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 720, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 96, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/MoFo"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 96, "lr": 0.01, "norm": true, "seq_len": 336, "patience": 10, "periodic": 96, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 192, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 96, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 336, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 96, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 720, "lr": 0.01, "norm": true, "seq_len": 336, "patience": 10, "periodic": 96, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/MoFo"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 64, "d_model": 24, "horizon": 96, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 144, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 16, "d_model": 24, "horizon": 192, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 144, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 256, "d_model": 12, "horizon": 336, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 144, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 64, "d_model": 24, "horizon": 720, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 144, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/MoFo"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 96, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 144, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 192, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 144, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 64, "d_model": 32, "horizon": 336, "lr": 0.015, "norm": true, "seq_len": 512, "patience": 10, "periodic": 144, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Solar.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.MoFo" --model-hyper-params '{"batch_size": 32, "d_model": 24, "horizon": 720, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 144, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Solar/MoFo"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.MoFo1" --model-hyper-params '{"batch_size": 16, "d_model": 256, "horizon": 96, "lr": 0.001, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.MoFo1" --model-hyper-params '{"batch_size": 16, "d_model": 96, "horizon": 192, "lr": 0.001, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.MoFo1" --model-hyper-params '{"batch_size": 16, "d_model": 96, "horizon": 336, "lr": 0.001, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.MoFo1" --model-hyper-params '{"batch_size": 16, "d_model": 256, "horizon": 720, "lr": 0.001, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/MoFo"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96}' --model-name "time_series_library.MoFo1" --model-hyper-params '{"batch_size": 16, "d_model": 108, "horizon": 96, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192}' --model-name "time_series_library.MoFo1" --model-hyper-params '{"batch_size": 16, "d_model": 108, "horizon": 192, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336}' --model-name "time_series_library.MoFo1" --model-hyper-params '{"batch_size": 16, "d_model": 128, "horizon": 336, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/MoFo"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720}' --model-name "time_series_library.MoFo1" --model-hyper-params '{"batch_size": 14, "d_model": 128, "horizon": 720, "lr": 0.01, "norm": true, "seq_len": 512, "patience": 10, "periodic": 24, "bias": 1, "cias": 1}' --adapter "MoFo_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/MoFo"

